### ISSUE TITLE
NPE occurs when printing tensors if *print-length* is nil.

### ISSUE THREAD

**Issue by jjttjj** [uncomplicate/deep-diamond#21] opened 2023-04-17 17:46 UTC
Not a high priority issue but I hit this and figured I would log it here.

I believe `*print-length*` defaults to nil in clojure, but some of the print methods in deep-diamond depend on it being set or they throw an NPE. For example, here:
https://github.com/uncomplicate/deep-diamond/blob/41913bf930bad92f8341ad679459827ac61ebf93/src/clojure/uncomplicate/diamond/internal/dnnl/tensor.clj#L521

**Comment by blueberry** [comment] 2023-04-18 18:40
Thanks. I'll see to fix it in the next release.

**Comment by matthewdowney** [comment] 2023-05-01 01:20
Just hit this also, I think this was the cause in #9 too.

**Comment by behrica** [comment] 2024-05-17 13:20
same for me. I am poking arrround , still blindly, in deep diamond,
but could not print my tensors, geeting NPEs

Now i see of course, having learned from #22 ,
That the "hello world" projects sets *print-length*

I would still think , that code should work even without having any of these set:
https://github.com/uncomplicate/deep-diamond/blob/9d6c9bf4411d998243c82c2c62426c6ad497a994/project.clj#L22

**Comment by blueberry** [comment] 2024-05-17 16:45
Fixed in the newest snapshot.

**Closed by blueberry** 2024-05-17 16:45 UTC
